---

# ansible-playbook semaphore.yml -i hosts --extra-vars "target=host"

- hosts: "{{ target }}"
  become: true
  remote_user: "{{ remote_user }}"
  vars_files: vars.yml
  roles:
    - system

    - firewall

    - { role: postgresql, when: semaphore_deployment_method == "systemd" } 

    - { role: semaphore, when: semaphore_deployment_method == "systemd" }

    - { role: docker, when: semaphore_deployment_method == "docker_compose" }

    - { role: docker-compose, when: semaphore_deployment_method == "docker_compose" }

    - { role: systemd, when: semaphore_deployment_method == "systemd" }

